name: BbangMap

on:
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-18.04

    steps:
      - name: Deploy deployment
        uses: actions/checkout@v2
        with:
          script: |
            sudo git config --global --add safe.directory ~/BBang-map-test
            sudo git config --global user.username ${{GITHUB_USERNAME}}
            sudo git config --global user.password ${{GITHUB_PASSWORD}}
            cd BBang-map-test
            sudo git checkout .
            sudo git pull origin main
            sudo npm install
            pm2 restart bbang-map-server
